---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment
spec:
  steps:
    - name: retrieve-yaml
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        mkdir k8s
        wget 'https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml' -O "k8s/run-steps-as-non-root.yaml"
  - name: extract-task
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        head -n 24 k8s/run-steps-as-non-root.yaml > "k8s/run-steps-as-non-root-task-only.yaml"
    - name: swap-image
      image: quay.io/ibmgaragecloud/alpine-curl
    script: |
        sed 's/image: ubuntu/image: quay.io\/ibmgaragecloud\/alpine-curl/g' k8s/run-steps-as-non-root-task-only.yaml > "k8s/run-steps-as-non-root-alpine-task.yaml"
        